<?php

namespace AppBundle\Repository;

/**
 * MentionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionsRepository extends \Doctrine\ORM\EntityRepository
{
}
