<?php

namespace AppBundle\Repository;

/**
 * SelectedArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectedArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
