<?php

namespace AppBundle\Repository;

/**
 * SelectedArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SelectedArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function articleShowIndex()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a FROM AppBundle:SelectedArticle a WHERE a.id = 4"
            )
            ->getResult();
    }

    public function articlesRightMenu()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a FROM AppBundle:SelectedArticle a WHERE a.id < 4 ORDER BY a.id DESC"
            )
            ->getResult();
    }
}
