<?php

namespace AppBundle\Repository;

/**
 * SiteInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
