<?php

namespace AppBundle\Repository;

/**
 * SubRubricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubRubricRepository extends \Doctrine\ORM\EntityRepository
{
    public function subRubriqueLeftMenu()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT sr FROM AppBundle:SubRubric sr WHERE sr.rubrique is null'
            )
            ->getResult();
    }
}
