imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.article_images: /uploads/images/articles
framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'

# FosUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:    [ ]
   #java: /usr/bin/java
    java: C:\Program Files\Java\jdk1.8.0_65\bin\java.exe
    filters:
        cssrewrite: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed.jar"        
            yui_js:
              jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        lessphp:
            file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"   
            apply_to: ".less$"
    assets:
        jquery_js:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"            
            filters: [?yui_js]
            output: js/jquery.min.js
           
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
            filters:
                - lessphp
                - cssrewrite
            output: css/bootstrap.css            

        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
            filters: [?yui_js]
            output: js/bootstrap.js             
        fonts_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        fonts_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        fonts_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        fonts_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"

            output: "fonts/glyphicons-halflings-regular.woff"

#Vich
vich_uploader:
    db_driver: orm
    mappings:
        article_images:
            uri_prefix:         '%app.path.article_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/articles'
            namer: vich_uploader.namer_uniqid


ivory_ck_editor:
    configs:
        SiteInfo:
            filebrowserBrowseRoute: 'elfinder'
            toolbar: "tool_article"
        article:
            filebrowserBrowseRoute: 'elfinder'
            toolbar: "tool_article"
    toolbars:
       configs:
           tool_article: [ "@texte",  "@puce" , "@other", "@web" ]
       items:
           texte: [ 'Bold', 'Italic', 'Underline' ,'TextColor', 'FontSize' ]
           puce:     [ 'NumberedList', 'BulletedList']
           other:     ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
           web: ['Image','Link', 'Unlink','Source']

easy_admin:
    site_name: '<img src="/img/logowhite.png" alt="Logo Axelle Mag" />'
    design:
        brand_color: 'dark'
        form_theme: 'vertical'
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'times', label: ''}
            - { name: 'new', label: 'Créer'}
    entities:
        Article:
            label: 'Articles'
            class: AppBundle\Entity\Article
            form:
                title: 'Créer/Modifier un article'
                fields:
                    - { type: 'group', css_class: 'col-sm-8'}
                    - { property: 'titre', label: "Titre de l'article", type_options: {required: true}}
                    - { property: 'contenu', type: 'ckeditor' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'imageFile', type: 'file' }
                    - video
                    - { property: 'subRubrique', label: 'Rubrique', type_options: {required: true } }
            list:
                title: 'Articles'
                max_results: 30
                fields:
                    - 'titre'
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - { property: 'datePost', label: 'Date'}
            show:
                title: 'Articles'
                fields:
                    - titre
                    - { property: 'datePost', label: 'Date'}
                    - contenu
                    - video
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }

        Rubrique:
            label: 'Sur-rubriques'
            class: AppBundle\Entity\Rubrique
            show:
                title: 'Sur-rubriques'
                fields:
                    - nom
            list:
                title: 'Sur-rubriques'
                fields:
                    - nom
            form:
                title: 'Créer/Modifier une sur-rubrique'
                fields:
                    - { type: 'group', css_class: 'col-sm-5'}
                    - { property: 'nom', label: 'Nom de la sur-rubrique', type_options: {required: true}}

        Sous_rubrique:
            label: 'Rubriques'
            class: AppBundle\Entity\SubRubric
            show:
                title: 'Rubriques'
                fields:
                    - { property: 'name', label: 'Nom'}
                    - { property: 'rubrique', label: 'Sur-rubrique'}
            list:
                title: 'Rubriques'
                fields:
                    - { property: 'name', label: 'Nom'}
#                    - { property: 'rubrique', label: 'Sur-rubrique'}
            form:
                title: 'Créer/Modifier une rubrique'
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Nom de la rubrique', type_options: {required: true}}
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'rubrique', label: 'Sur-rubrique'}

        Utilisateur:
            class: AppBundle\Entity\User
            list:
                fields:
                    - { property: 'username', label: "Nom de l'utilisateur"}
                    - email
                    - { property: 'enabled', label: "Compte activé"}
                    - { property: 'lastLogin', label: 'Date de dernière connexion'}
            form:
                title: 'Créer/Modifier un utilisateur'
                fields:
                    - { type: 'group', css_class: 'col-sm-5' }
                    - { property: 'username', label: "Nom de l'utilisateur"}
                    - email
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'password', type_options: { required: true } }

        Info_Site:
            label: 'Informations'
            class: AppBundle\Entity\SiteInfo
            list:
                title: 'Informations'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'col-sm-1' }
                fields:
                    - { property: 'A_propos', type: 'raw'}
                    - Facebook
                    - Twitter
                    - Instagram
                    - Mail
            form:
                title: 'Editer les informations'
                fields:
                    - { type: 'group', css_class: 'col-sm-8' }
                    - { property: 'A_propos', type: 'ckeditor' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - facebook
                    - twitter
                    - instagram
                    - mail
            disabled_actions: ['new', 'delete', 'search']

        Contact:
            label: 'Contact'
            class: AppBundle\Entity\Contact
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'col-sm-1' }
                fields:
                    - { property: 'content', label: 'Contenu', type: 'raw', css_class: 'col-sm-10' }
            form:
                title: 'Editer les contacts'
                fields:
                    - { property: 'content', label: 'Contenu', type: 'ckeditor', type_options: {required: true} }
            disabled_actions: ['new', 'delete', 'search']

        Mentions:
            label: 'Mentions légales'
            class: AppBundle\Entity\Mentions
            list:
                title: 'Mentions légales'
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'col-sm-1' }
                fields:
                    - { property: 'content', label: 'Contenu', type: 'raw', css_class: 'col-sm-10'}
            form:
                title: 'Editer les mentions légales'
                fields:
                    - { property: 'Content', label: 'Contenu', type: 'ckeditor', type_options: {required: true} }
            disabled_actions: ['new', 'delete', 'search']

        Selected_Article:
            label: 'Articles en avant'
            class: AppBundle\Entity\SelectedArticle
            list:
                title: 'Articles en avant'
                fields:
                    - { property: 'nom', label: 'Emplacement' }
                    - { property: 'article', label: "Titre de l'article sélectionné"}
            form:
                title: 'Articles en avant'
                fields:
                    - {property: 'article', label: "Article à mettre en avant", orderby: 'DESC' }
            disabled_actions: ['new', 'delete', 'search']
            
fm_elfinder:
   #assets_path: / # default is /assets, this is where css/js elfinder files are
   instances:
       default:
           locale: %locale% # defaults to current request locale
           editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
           #editor_template: custom template for your editor # default null
           #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
           #fullscreen: true|false # default is true, applies to simple and ckeditor editors
           #theme: smoothness # jquery theme, default is 'smoothness'
           include_assets: true # disable if you want to manage loading of javascript and css assets manually
           #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
           connector:
               #debug: true|false # defaults to false
               roots:       # at least one root must be defined, defines root filemanager directories
                   uploads:
                       #show_hidden: true|false # defaults to false, hides dotfiles
                       driver: LocalFileSystem
                       path: uploads
                       upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                       upload_deny: ['all']
                       upload_max_size: 2M # also file upload sizes restricted in php.ini

